# Generated by Django 3.2.7 on 2023-06-08 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_num', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.games')),
            ],
            options={
                'unique_together': {('round_num', 'game_id')},
            },
        ),
        migrations.CreateModel(
            name='PlayerRounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('choochoo', models.BooleanField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.games')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.players')),
                ('round_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.rounds')),
            ],
            options={
                'unique_together': {('player_id', 'round_num', 'game_id')},
            },
        ),
    ]
